# base image
FROM node:12.2.0-alpine

# install and cache app dependencies
COPY package.json package.json
RUN npm install --silent

# copy src files
COPY . .

# set port
EXPOSE 3000

# start app
CMD ["npm", "start"]